package carnerero.agustin.cuentaappandroid.main.model

enum class IconOptions {
    HOME,
    SEARCH,
    SEARCH_DELETE,
    SEARCH_UPDATE,
    SETTINGS,
    PROFILE,
    NEW_AMOUNT,
    CHANGE_CURRENCY,
    EDIT_ACCOUNTS,
    INCOME_OPTIONS,
    EXPENSE_OPTIONS,
    TRANSFER,
    BARCHART,
    PIE_CHART,
    CALCULATOR,
    SETTING_ACCOUNTS,
    DELETE_ACCOUNT,
    ABOUT,
    ABOUT_DESCRIPTION,
    EXIT,
    ENTRIES,
    ENTRIES_TO_DELETE,
    ENTRIES_TO_UPDATE,
    EMAIL,
    SELECT_CATEGORIES,
    SELECT_ACCOUNTS,
    CATEGORY_EXPENSE_CONTROL,
    ACCOUNT_EXPENSE_CONTROL

}